### ISSUE TITLE
BAIFA 爬蟲交接文件

### ISSUE THREAD

**Issue by gibbs-shih** [CAFECA-IO/BAIFA-web-crawling#79]
baifa 網頁
- https://baifa.io/en/app/chains

db schema 文件
- https://github.com/CAFECA-IO/Documents/tree/main/BFA/db_schema

資料庫關聯圖
- https://github.com/CAFECA-IO/Documents/blob/main/BFA/BFAER00001.md
- https://github.com/CAFECA-IO/Documents/blob/main/BFA/BFAER00002.md

系統流程圖
- https://github.com/CAFECA-IO/Documents/blob/main/BFA/BFASD00001.md
- https://github.com/CAFECA-IO/Documents/blob/main/BFA/BFASD00002.md
- https://github.com/CAFECA-IO/Documents/blob/main/BFA/BFASD00003.md
- https://github.com/CAFECA-IO/Documents/blob/main/BFA/BFASD00004.md

程式碼使用
- https://github.com/CAFECA-IO/BAIFA-web-crawling/blob/develop/README.md

鏈資料
- BOLT
  chain_id: 58017
  chain_name: "BOLT"
  symbol: "BLT"
  decimal: 18
  rpc: "https://bolt.baifa.io/"

- iSunCoin
  chain_id: 8017
  chain_name: "iSunCoin"
  symbol: "ISC"
  decimal: 18
  rpc: "https://isuncoin.baifa.io/"

資料庫連線資訊, 兩台雲端連線資訊
- 另行傳給 jacky

**Comment by gibbs-shih** [comment]
爬蟲的票：
## :books:BAIFA web crawling，規劃： -- pt，完成： -- pt (實際 -- pt)

### BAIFA web crawling - iSunCloud鏈爬蟲開發計劃
需求分析和爬蟲策略設計，預估 6pt:
- [x] 確定iSunCloud鏈的接口和數據特點（2pt）[#1](https://github.com/CAFECA-IO/BAIFA_web_crawling/issues/1)
- [x] 設計針對iSunCloud鏈的爬蟲策略，包括數據同步機制（2pt）[#2](https://github.com/CAFECA-IO/BAIFA_web_crawling/issues/2)
- [x] 設計針對iSunCloud鏈的爬蟲策略，包括數據處理邏輯（2pt）[#3](https://github.com/CAFECA-IO/BAIFA_web_crawling/issues/3)

爬蟲實現，預估 12pt:
- [x] 相關爬蟲環境設置（3pt）[#4](https://github.com/CAFECA-IO/BAIFA_web_crawling/issues/4)
- [x] 編寫針對iSunCloud鏈的爬蟲代碼，處理API調用（3pt）[#5](https://github.com/CAFECA-IO/BAIFA_web_crawling/issues/5)
- [x] 編寫針對iSunCloud鏈的爬蟲代碼，處理數據抓取（3pt）[#6](https://github.com/CAFECA-IO/BAIFA_web_crawling/issues/6)
- [x] 編寫針對iSunCloud鏈的爬蟲代碼，處理初步的數據格式化（3pt）[#7](https://github.com/CAFECA-IO/BAIFA_web_crawling/issues/7)

數據處理和整合，預估 16pt:
- [x] 確保爬取的數據能夠被BAIFA系統統一處理（8pt）[#8](https://github.com/CAFECA-IO/BAIFA_web_crawling/issues/8)
- [ ] 整合被BAIFA系統處理後的資料（8pt）[#9](https://github.com/CAFECA-IO/BAIFA_web_crawling/issues/9)

數據庫設計與模型建立，預估 10pt:
- [x] 設計數據庫模型以支持多種事件類型（2pt）[#10](https://github.com/CAFECA-IO/BAIFA_web_crawling/issues/10)
- [x] 建立數據庫模型以支持多種事件類型（3pt）[#11](https://github.com/CAFECA-IO/BAIFA_web_crawling/issues/11)
- [x] 進行初步測試（5pt）[#12](https://github.com/CAFECA-IO/BAIFA_web_crawling/issues/12)

測試和優化，預估 10pt:
- [x] 對iSunCloud鏈的爬蟲進行單元測試及誤差處理（5pt）[#13](https://github.com/CAFECA-IO/BAIFA_web_crawling/issues/13)
- [ ] 對iSunCloud鏈的爬蟲進行集成測試及誤差處理（5pt）[#14](https://github.com/CAFECA-IO/BAIFA_web_crawling/issues/14)

部署和文檔編寫，預估 6pt:
- [x] 部署爬蟲到測試環境（2pt）[#15](https://github.com/CAFECA-IO/BAIFA_web_crawling/issues/15)
- [ ] 進行最終的整合測試（2pt）[#16](https://github.com/CAFECA-IO/BAIFA_web_crawling/issues/16)
- [ ] 撰寫技術文檔和操作指南（2pt）[#17](https://github.com/CAFECA-IO/BAIFA_web_crawling/issues/17)

新增：
- [x] 調整BFASD0001-0004 (3pt) [#18](https://github.com/CAFECA-IO/BAIFA_web_crawling/issues/18)
- [x] SQLite資料欄位圖 (2pt) [#20](https://github.com/CAFECA-IO/BAIFA_web_crawling/issues/20)
- [x] 建立資料表關聯（2pt）[#31](https://github.com/CAFECA-IO/BAIFA_web_crawling/issues/31)
- [x] 解析資料表 toekn_transfers、token_balances（2pt）[#30](https://github.com/CAFECA-IO/BAIFA_web_crawling/issues/30)
- [x] 解析資料表 red_flags、currencies、transactions（2pt）[#29](https://github.com/CAFECA-IO/BAIFA_web_crawling/issues/29)
- [x] 解析資料表 review_datas、risk_records、evidences（2pt）[#28](https://github.com/CAFECA-IO/BAIFA_web_crawling/issues/28)
- [x] 解析資料表 black_lists、chains、addresses（2pt）[#27](https://github.com/CAFECA-IO/BAIFA_web_crawling/issues/27)
- [x] 解析資料表 contracts、public_tags、blocks（2pt）[#26](https://github.com/CAFECA-IO/BAIFA_web_crawling/issues/26)
- [x] 更新文件DB schema (2pt) [#33](https://github.com/CAFECA-IO/BAIFA_web_crawling/issues/33)
- [x] 需要補齊的參數 (8pt) [#34](https://github.com/CAFECA-IO/BAIFA_web_crawling/issues/34)
- [x] 重構transactions \ transfers \ balances 流程 (8pt) [36](https://github.com/CAFECA-IO/BAIFA_web_crawling/issues/36)
- [x] `Yang` 提供 evidences - state 參數 (3pt) [#37](https://github.com/CAFECA-IO/BAIFA_web_crawling/issues/37)
- [x] `Yang` 將 evidence 產生的內容放進 evidences 資料表 content 欄位 (3pt) [#38](https://github.com/CAFECA-IO/BAIFA_web_crawling/issues/38)
- [x] 確認 evidence transaction 的 type 是否改變及確認 evidences 資料表其他所需資訊 (5pt) [#39](https://github.com/CAFECA-IO/BAIFA_web_crawling/issues/39)
- [x] 解析 table：currencies - price、volume_in_24h、holder_count 值 (8pt) [#40](https://github.com/CAFECA-IO/BAIFA_web_crawling/issues/40)
- [ ] 解析 table：currencies - risk_level 值 (5pt) [#41](https://github.com/CAFECA-IO/BAIFA_web_crawling/issues/41)
- [x] 解析 table：addresses - score 值 (5pt) [#42](https://github.com/CAFECA-IO/BAIFA_web_crawling/issues/42)
- [x] review_datas schema 需要修改 (1pt) [#705](https://github.com/CAFECA-IO/BAIFA/issues/705)
- [x] 運用資料庫 transaction 機制, 確保爬蟲及解析到的資料完整 (5pt) [#43](https://github.com/CAFECA-IO/BAIFA_web_crawling/issues/43)
- [x] 修改 contracts 資料表 (5pt) [#44](https://github.com/CAFECA-IO/BAIFA_web_crawling/issues/44)
- [x] 整合爬取報表內容及塞入content程式碼 (8pt) [#45](https://github.com/CAFECA-IO/BAIFA_web_crawling/issues/45)
- [x] token balances DB ＆ crawler 調整 (5pt) [#859](https://github.com/CAFECA-IO/BAIFA/issues/859)
- [x] codes table 跟文件不一致 (transactions type) (1pt) [#894](https://github.com/CAFECA-IO/BAIFA/issues/894)
- [x] miner 需要被紀錄在 addresses table 上 (5pt) [#895](https://github.com/CAFECA-IO/BAIFA/issues/895)
- [x] bug - 解決 timeout 問題 (3pt) [#46](https://github.com/CAFECA-IO/BAIFA_web_crawling/issues/46)
- [ ] 解析 table：currencies - price (5pt) [#48](https://github.com/CAFECA-IO/BAIFA_web_crawling/issues/48)
- [x] 修改 evidences table, content column, report 格式 (5pt) [#49](https://github.com/CAFECA-IO/BAIFA_web_crawling/issues/49)
- [x] 串接 tidebit event 資料 （5pt） [#50](https://github.com/CAFECA-IO/BAIFA-web-crawling/issues/50)
- [ ] 顯示 tidebit event 資料於報表中 （8pt）[#51](https://github.com/CAFECA-IO/BAIFA-web-crawling/issues/51)
- [x] 修改 prisma client instance 為共用 （3pt）[#52](https://github.com/CAFECA-IO/BAIFA-web-crawling/issues/52)
- [x] 提高 transaction 機制時間及 errorPath 方式修改 (3pt）[#53](https://github.com/CAFECA-IO/BAIFA-web-crawling/issues/53)
- [x] Bug - evidences table, content column, report 時間及金額問題 (8pt) [#56](https://github.com/CAFECA-IO/BAIFA-web-crawling/issues/56)
- [x] [Bug] 爬蟲連線 isuncoin.baifa.io 若失敗會造成爬蟲斷掉 （5pt）[#57](https://github.com/CAFECA-IO/BAIFA-web-crawling/issues/57)
- [x] 新增 iSunCoin 測試網 BOLT，部署爬蟲（3pt）[#59](https://github.com/CAFECA-IO/BAIFA-web-crawling/issues/59)
- [x] db 調整欄位加入 chain id （2pt）[#60](https://github.com/CAFECA-IO/BAIFA-web-crawling/issues/60)
- [x] 程式碼加入儲存 chain id（2pt）[#61](https://github.com/CAFECA-IO/BAIFA-web-crawling/issues/61)
- [x] 新增程式碼用 chain id 進行篩選, 以在資料庫中分出各種 chain（3pt）[#63](https://github.com/CAFECA-IO/BAIFA-web-crawling/issues/63)
- [x] 拉出相關設定檔, chain 資料由 chain info constant 而來 （1pt）[#64](https://github.com/CAFECA-IO/BAIFA-web-crawling/issues/64)
- [x] 修改 readme（1pt）[#65](https://github.com/CAFECA-IO/BAIFA-web-crawling/issues/65)
- [x] 檢查 db 邏輯（5pt）[#66](https://github.com/CAFECA-IO/BAIFA-web-crawling/issues/66)
- [x] 調整 currency db（2pt）[#67](https://github.com/CAFECA-IO/BAIFA-web-crawling/issues/67)
- [x] 調整 currency 爬蟲（8pt）[#68](https://github.com/CAFECA-IO/BAIFA-web-crawling/issues/68)
- [x] 修正 currency total supply 統計錯誤（2pt）[#69](https://github.com/CAFECA-IO/BAIFA-web-crawling/issues/69)
- [x] 調整 .env.sample 及 README.md（3pt）[#70](https://github.com/CAFECA-IO/BAIFA-web-crawling/issues/70)
- [x] 修改 schema 文件, 關聯圖（2pt）[#71](https://github.com/CAFECA-IO/BAIFA-web-crawling/issues/71)
- [x] reward 加入 token_balances（3pt）[#72](https://github.com/CAFECA-IO/BAIFA-web-crawling/issues/72)
- [x] BAIFA 爬蟲 - 轉帳時轉出方的錢沒有減少（3pt）[#73](https://github.com/CAFECA-IO/BAIFA-web-crawling/issues/73)
- [x] BAIFA 爬蟲 - 0x0...不需要給 reward（5pt）[#74](https://github.com/CAFECA-IO/BAIFA-web-crawling/issues/74)
- [x] db連線出錯, 造成解析程序停止 (5pt) [#76](https://github.com/CAFECA-IO/BAIFA-web-crawling/issues/76)
- [ ] 重構 db 統一操作 (8pt) [#77](https://github.com/CAFECA-IO/BAIFA-web-crawling/issues/77)

**Comment by gibbs-shih** [comment]
![CleanShot 2024-09-24 at 11 35 35](https://github.com/user-attachments/assets/2a335cca-6850-40e2-9129-23d8daed1c02)

**Comment by gibbs-shih** [comment]
![CleanShot 2024-09-24 at 15 10 36](https://github.com/user-attachments/assets/5ecb5ac0-6cea-447b-a9bb-ec89481ee496)

**Comment by gibbs-shih** [comment]
![CleanShot 2024-09-24 at 15 24 03](https://github.com/user-attachments/assets/a2ff829b-2592-40d6-9959-80ce27babe57)

**Comment by gibbs-shih** [comment]
![CleanShot 2024-09-24 at 15 44 24](https://github.com/user-attachments/assets/f8c24c0c-8cf6-42b1-9a75-a7540327f7c7)
